project:
  type: website

website:
  title: "MŠ Bajka"
  site-url: "https://ms-bajka.sk"
  description: "Materská škola Bajka - miesto, kde rastú úsmevy"
  navbar:
    background: primary
    pinned: true
    left:
      - href: index.qmd
        text: "Domov"
      - href: o-nas.qmd
        text: "O nás"
      - href: dokumenty.qmd
        text: "Dokumenty"
      - href: galeria.qmd
        text: "Galéria"
      - href: kontakt.qmd
        text: "Kontakt"
  page-footer:
    left: "© 2026 Materská škola Bajka"
    center: "Vytvorené s láskou pre vaše deti"
    right: "Vytvorené - Bc. Marek Penzeš"

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header: partials/head.html
    include-after-body: partials/scripts.html
    toc: false
    page-layout: full
    fontsize: 1.05em
    linkcolor: "#ee6c4d"
