---
title: "O nás"
---

::: {.hero}
# O našej škôlke

Spoznajte náš tím, hodnoty a priestory.
:::

::: {.section .reveal}
## Náš príbeh

Materská škola Bajka funguje od roku XXXX a počas tejto doby prešlo
našimi triedami už niekoľko desiatok detí. Zakladáme si na priateľskom
prostredí a individuálnom prístupe k deťom.
:::

::: {.section .reveal}
## Informácie o škôlke

Materská škola v zriaďovateľskej pôsobnosti obce Bajka poskytuje poldennú
výchovú a vzdelávanie deťom spravidla od troch do šiestich rokov. Na
území obce je zriadená jedna materská škola bez právnej subjektivity.

Dieťa sa do materskej školy prijíma na základe písomnej žiadosti zákonného
zástupcu, ktorú predloží riaditeľke materskej školy spolu s potvrdením
o zdravotnom stave dieťaťa od všeobecného lekára pre deti a dorast alebo je možné podať prihlášku elektronicky cez: 
https://eprihlasky.iedu.sk/  
Ak ide o dieťa so špeciálnymi výchovno – vzdelávacími potrebami, zákonný zástupca
predloží aj vyjadrenie príslušného zariadenia výchovného poradenstva
a prevencie.

Do materskej školy sa prijímajú deti pre nasledujúci školský rok v termíne
od 1. mája do 31. mája, alebo pokiaľ to kapacitné možnosti materskej školy
dovolia, aj priebežne. Miesto a termín podávania žiadosti pre nasledujúci
školský rok zverejní riaditeľka po dohode so zriaďovateľom na budove
materskej školy a inom verejne dostupnom mieste.
:::


::: {.section .reveal}
## Naše priestory

Objekt tvorí vstupná chodba, malá chodba so šatňou, jedna trieda, detská umyváreň s toaletami, spoločná umyváreň so sociálnym zariadením pre pedagogického zamestnanca a nepedagogických zamestnancov vrátane odkladacie priestoru pre upratovacie náradie, čistiace prostriedky a ostatné upratovacie pomôcky a spotrebiče, odkladací priestor pre rôzne pomôcky, jedáleň a kuchyňa.
:::


